# Stage 1: Build JAR
FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

# Copy pom first — dependencies cache honge
COPY pom.xml .
RUN mvn dependency:go-offline -B


# Copy source and build
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/complianceiq.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]